name: Separated Jobs (lint, build, test, deploy)

on:
  [push, workflow_dispatch]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from our branch
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  test:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from our branch
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from our branch
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from our branch
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Deploy (pseudo) build
        run: echo "Code deployed!"