name: Basic Deployment

on:
  [workflow_dispatch]

jobs:
  all-in-one:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from our branch
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Deploy (pseudo) build
        run: echo "Code deployed!"